# -*- coding: utf-8 -*-
"""MFG 598 Data Cleaning (1).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10cZx-yqYioaDQYLXU7IjPXNF7YZb6UDD
"""



from google.colab import drive
drive.mount('/content/drive')

import pandas as pd
import numpy as np
import math
import seaborn as sns

df=pd.read_csv("/content/drive/MyDrive/python project/fuel.csv")

df

list1=[]
for x in df.columns:
  #print(x,df[x].isnull().sum())
  if df[x].isnull().sum()>0:
    print(x,df[x].dtype)
    list1.append(x)

columns_remove=[]

for x in list1:
  if df[x].dtype==object:
    columns_remove.append(x)

columns_remove

df.drop(columns=columns_remove,inplace=True)

df

for x in df.columns:
  if df[x].isnull().sum()>0:
    print(x,df[x].isnull().sum())

columns=["supercharger",
"fuel_type_2",
"start_stop_technology",
"electric_motor",
"manufacturer_code",
"vehicle_charger",
"alternate_charger",
"range_ft2"]

df.drop(columns=columns,inplace=True)

df

for x in df.columns:
  print(x,df[x].isnull().sum())

columns=["engine_cylinders",
"engine_displacement"]

engine_cylinders_column=df["engine_cylinders"].to_numpy().tolist()

value1list=[]

engine_cylinders_column

for x in engine_cylinders_column:
  y=str(x)

  if y!='nan':
    value1list.append(y)

value2list=[]

for x in value1list:
  value2list.append(float(x))

value2list

mean1=np.mean(value2list)

engine_displacement=df["engine_displacement"].to_numpy().tolist()

value3list=[]

for x in engine_displacement:
  y=str(x)
  if y!='nan':
    value3list.append(y)

value4list=[]

for x in value3list:
  value4list.append(float(x))

mean2=np.mean(value4list)

mean2=math.floor(mean2)

mean1=math.floor(mean1)

for x in df['engine_displacement']:
  y=str(x)
  if y=='nan':
    df.replace(x,mean2,inplace=True)

for x in df['engine_cylinders']:
  y=str(x)
  if y=='nan':
    df.replace(x,mean1,inplace=True)

df['engine_cylinders']

df['engine_displacement']

for x in df.columns:
  if df[x].isnull().sum()>0:
    print(x)

df.to_csv("/content/drive/MyDrive/python project/df.csv")